
/data/jinjianjun/.pyenv/versions/3.6.5/bin/evaluate_assembly_using_mapping.py -1 ERR2206741_1.fastq.gz -2 ERR2206741_2.fastq.gz -o NOVOPlasty-plastome/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated -f NOVOPlasty-plastome/K47/ERR2206741-plastome/Contigs_1_novoplasty.plastome.fasta -t 16 --continue --draw -c no --plot-title ERR2206741-NOVOPlasty --plot-subtitle "Used result file: Contigs_1_novoplasty.plastome.fasta      Options: K-mer=47, Genome Range=15000-180000      Result status: 0 contig(s)"

2019-09-04 01:42:52,997 - INFO: Making  - bowtie2 index ...
2019-09-04 01:42:53,087 - ERROR: 
Settings:
  Output files: "NOVOPlasty/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated/modified.index.*.bt2l"
  Line rate: 7 (line is 128 bytes)
  Lines per side: 1 (side is 128 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 12345
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  NOVOPlasty-plastome/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated/modified.fasta
Warning: Empty fasta file: 'NOVOPlasty/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated/modified.fasta'
Warning: All fasta inputs were empty
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: /data/jinjianjun/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/GetOrganelleDep/linux/bowtie2/bowtie2-build-l --wrapper basic-0 --seed 12345 NOVOPlasty-plastome/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated/modified.fasta NOVOPlasty-plastome/K47/NOVOPlasty-K47--ERR2206741-plastome--evaluated/modified.index 

